#!/bin/bash
# START WITH UNSETTING THE AWS PATHS IF THEY ARE SET (allows more than one
# checkout of this repo and switching between them)
aws_path="${EC2_HOME}/bin:${AWS_AUTO_SCALING_HOME}/bin:${AWS_ELB_HOME}/bin:${AWS_AMITOOL_HOME}/bin:${AWS_CLOUDWATCH_HOME}/bin"
export PATH=$(echo $PATH | sed "s#:${aws_path}##g")

# NOW START THE WORK
DIR=$(dirname ${BASH_SOURCE})
DIR=$($DIR/../bin/expand_path.rb ./$DIR/../)

if [ -f $DIR/etc/secrets ]; then source $DIR/etc/secrets; fi

export JAVA_HOME=`/usr/libexec/java_home`
export EC2_REGION='eu-west-1'

export EC2_PRIVATE_KEY="${DIR}/etc/private_key.pem"
export EC2_CERT="${DIR}/etc/cert.pem"

export EC2_HOME="${DIR}/opt/ec2-api"
export AWS_AUTO_SCALING_HOME="${DIR}/opt/ec2-as"
export AWS_ELB_HOME="${DIR}/opt/ec2-elb"
export AWS_AMITOOL_HOME="${DIR}/opt/ec2-ami"
export AWS_CLOUDWATCH_HOME="${DIR}/opt/ec2-cw"

aws_path="${EC2_HOME}/bin:${AWS_AUTO_SCALING_HOME}/bin:${AWS_ELB_HOME}/bin:${AWS_AMITOOL_HOME}/bin:${AWS_CLOUDWATCH_HOME}/bin"
export PATH="${PATH}:${aws_path}"
